name: Build AmneziAWG OpenWrt Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SDK_URL: https://downloads.openwrt.org/releases/24.10.2/targets/rockchip/armv8/openwrt-sdk-24.10.2-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
  SDK_FILE: openwrt-sdk.tar.zst
  SDK_DIR: openwrt-sdk-24.10.2-rockchip-armv8

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget python3 python3-pip zstd

    - name: Download and Extract SDK
      run: |
        wget -O $SDK_FILE $SDK_URL
        tar -I zstd -xf $SDK_FILE
        
    - name: Setup SDK
      run: |
        cd $SDK_DIR
        # Update feeds.conf
        echo "src-git-full packages https://git.openwrt.org/feed/packages.git" > feeds.conf.default
        echo "src-git-full luci https://git.openwrt.org/project/luci.git" >> feeds.conf.default
        echo "src-git-full routing https://git.openwrt.org/feed/routing.git" >> feeds.conf.default
        echo "src-git-full telephony https://git.openwrt.org/feed/telephony.git" >> feeds.conf.default
        # Add amneziawg feed
        echo "src-link amneziawg $GITHUB_WORKSPACE/amneziawg" >> feeds.conf.default
        
    - name: Clone AmneziAWG
      run: |
        git clone https://github.com/amnezia-vpn/amneziawg-openwrt.git amneziawg

    - name: Update and Install Feeds
      run: |
        cd $SDK_DIR
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Configure Build
      run: |
        cd $SDK_DIR
        # Configure for amneziawg packages
        cat > .config <<'EOF'
        CONFIG_ALL=y
        CONFIG_PACKAGE_amneziawg=y
        CONFIG_PACKAGE_amneziawg-tools=y
        CONFIG_PACKAGE_kmod-amneziawg=y
        EOF
        make defconfig

    - name: Build Packages
      run: |
        cd $SDK_DIR
        make package/amneziawg/{clean,compile} V=s
        make package/amneziawg-tools/{clean,compile} V=s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: amneziawg-packages
        path: ${{ env.SDK_DIR }}/bin/packages/**/amneziawg*
        retention-days: 7

    - name: Upload Build Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          ${{ env.SDK_DIR }}/logs/
          ${{ env.SDK_DIR }}/.config
        retention-days: 7
