name: Build AmneziAWG OpenWrt Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SDK_URL: https://downloads.openwrt.org/releases/24.10.2/targets/rockchip/armv8/openwrt-sdk-24.10.2-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
  SDK_FILE: openwrt-sdk.tar.zst
  SDK_DIR: openwrt-sdk-24.10.2-rockchip-armv8

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils-extra python3-setuptools rsync unzip zlib1g-dev \
          file wget zstd

    - name: Download and Setup SDK
      run: |
        wget -O $SDK_FILE $SDK_URL
        mkdir -p $SDK_DIR
        tar -I zstd -xf $SDK_FILE
        mv openwrt-sdk-* $SDK_DIR

    - name: Setup Build Environment
      run: |
        cd $SDK_DIR
        # Create feeds.conf
        cat > feeds.conf <<EOF
        src-git base https://git.openwrt.org/openwrt/openwrt.git
        src-git packages https://git.openwrt.org/feed/packages.git
        src-git luci https://git.openwrt.org/project/luci.git
        src-git routing https://git.openwrt.org/feed/routing.git
        src-git telephony https://git.openwrt.org/feed/telephony.git
        EOF
        
        # Update feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone AmneziAWG
      run: |
        cd $SDK_DIR/package
        git clone https://github.com/amnezia-vpn/amneziawg-openwrt.git amneziawg
        
    - name: Configure Build
      run: |
        cd $SDK_DIR
        cat > .config <<'EOF'
        CONFIG_ALL_NONSHARED=y
        CONFIG_PACKAGE_amneziawg=y
        CONFIG_PACKAGE_amneziawg-tools=y
        CONFIG_PACKAGE_kmod-amneziawg=y
        EOF
        make defconfig

    - name: Build Packages
      run: |
        cd $SDK_DIR
        make package/amneziawg/{clean,compile} V=s
        make package/amneziawg-tools/{clean,compile} V=s

    - name: Package Artifacts
      run: |
        cd $SDK_DIR/bin/packages/*
        find . -name "amneziawg*.ipk" -exec cp {} $GITHUB_WORKSPACE/ \;

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: amneziawg-packages
        path: amneziawg*.ipk
        retention-days: 5

    - name: Upload Build Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          ${{ env.SDK_DIR }}/logs/
          ${{ env.SDK_DIR }}/.config
        retention-days: 1
